### ISSUE TITLE
Nil pointer dereference during `corteza-server settings list` and `settings export`

### ISSUE THREAD

**Issue by truemerrill** [cortezaproject/corteza-server#153]
**Describe the bug**
`corteza-server` panics with a runtime error when executing `corteza-server settings export <filename.json>` or `corteza-server settings list`.

**To Reproduce**
I have a locally running corteza instance using `docker-compose`.  The container with `corteza-server` is named `corteza_server`. 

```
❯ docker --version
Docker version 20.10.5, build 55c4c88
❯ docker exec -it corteza_server corteza-server version
2020.12.3
❯ docker exec -it corteza_server corteza-server settings list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe2f045]

goroutine 1 [running]:
github.com/cortezaproject/corteza-server/system/commands.Settings.func1(0xc0004e2280, 0x20a1ee0, 0x0, 0x0)
	/drone/src/system/commands/settings.go:33 +0x165
github.com/spf13/cobra.(*Command).execute(0xc0004e2280, 0xc00011c170, 0x0, 0x0, 0xc0004e2280, 0xc00011c170)
	/drone/src/vendor/github.com/spf13/cobra/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2000c20, 0x0, 0xffffffff, 0xc00010e058)
	/drone/src/vendor/github.com/spf13/cobra/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/drone/src/vendor/github.com/spf13/cobra/command.go:800
github.com/cortezaproject/corteza-server/app.(*CortezaApp).Execute(...)
	/drone/src/app/cli.go:69
main.main()
	/drone/src/cmd/corteza/main.go:13 +0x3b
```

**Expected behavior**
A list of all of the corteza settings

**Comment by darh** [comment]
Fixed w/ 5dd3fd6e. Will take a week or so to schedule this to next release (so, most likely 2020.12.4).
You can export settings directly from the db if you need to do it now (with mysql dump command from settings table).
